geekshop/authapp/urls.py
from django.urls import path
from django.urls import re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='product')),
    path('contacts/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

geekshop/ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product

class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'SRP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'forming'),
        (SENT_TO_PROCEED, 'sent to proceed'),
        (PROCEEDED, 'proceeded'),
        (PAID, 'paid'),
        (READY, 'ready'),
        (CANCEL, 'canceled'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='created', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='updated', auto_now=True)
    status = models.CharField(verbose_name='status',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='active', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'order'
        verbose_name_plural = 'orders'

    def __str__(self):
        return 'Current order: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='orderitems',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='product',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='quantity',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

geekshop/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/ordersapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm

class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'order/review'
        return context


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            data['orderitems'] = OrderFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:orders_list'))

geekshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css%}
        <link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.min.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">
        <script src="https://kit.fontawesome.com/8fece0c8ba.js"></script>
    {% endblock %}
    {% block js %}
        <script src = "{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src = "{% static 'js/orders_scripts.js' %}"></script>
    {% endblock%}
</head>
<body>
    <div class="order_container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="category_delete">
        <div> Are you sure you delete?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">cancel</a>
        </button>
    </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img src="{{ item.product.image|media_folder_products }}" alt="{{ item.product.short_desc}}" height="125px">
                <span class="category_name">
                    {{ item.product.category.name }}
                </span>
                <span class="product_name">{{ item.product.name}}</span>
                <span class="product_price">
                    $&nbsp;{{ item.product.price }}
                </span>
                <span class="product_quantity">
                    x {{ item.quantity }} items
                </span>
                <span class="product_cost">
                    = $&nbsp;{{ item.get_product_cost }}
                </span>
            </div>
        {% endfor %}
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>

                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="save" class="btn btn-default btn-round form-control last">save</button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="h2 text-center head">
        Your orders,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            User
        {% endif %}
    </div>
    <table class="table order_list">
        <thead>
            <tr>
                <th>ID</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <td class="td1 orders_list">{{item.pk }}</td>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display}}</td>
                        <td>
                            <a href="{% url 'ordersapp:order_read' item.pk %}">view</a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_update' item.pk %}">
                                edit
                            </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_delete' item.pk %}">
                                delete
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            main
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:order_create' %}">
            new
        </a>
    </button>
{% endblock %}