geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/',
         adminapp.ProductCategoryCreateView.as_view(),
         name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.ProductCategoryUpdateView.as_view(),
         name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.ProductCategoryDeleteView.as_view(),
         name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from django.urls import re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='product')),
    path('contacts/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.product, name='index'),
    path('category/<int:pk>/', mainapp.product, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.product, name='page'),
    path('product-details/<int:pk>/', mainapp.productdet, name='productdet'),
]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Category name',
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name="Description",
                                   blank=True)
    is_active = models.BooleanField(verbose_name='active', default=True)


    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Product name',
                            max_length=128)
    image = models.ImageField(upload_to='products_image', blank=True)
    short_desc = models.CharField(verbose_name='short product description',
                                  max_length = 100, blank=True)
    description = models.TextField(verbose_name='Product description',
                                   blank=True)
    price = models.DecimalField(verbose_name='Product price',
                                max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='storage quantity', default=0)
    is_active = models.BooleanField(verbose_name='active', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import json
import random
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from basketapp.models import Basket
from .models import ProductCategory, Product

# Create your views here.


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.filter(is_active=True,
                                      category__is_active=True)
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category,
                                           is_active=True,
                                           category__is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    products = Product.objects.filter(is_active=True,
                                      category__is_active=True)[:6]

    context = {
        'page_title': 'interior: home page',
        'products': products,
    }
    return render(request, 'mainapp/index.html', context)


def product(request, pk=None, page = 1):
    print(pk)
    categories = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).order_by('price')
            category = {
                'pk': 0,
                'name': 'all'
            }
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk,
                                              is_active=True,
                                              category__is_active=True).order_by('price')
        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(2)
        context = {
            'page_title': 'interior: products',
            'products': products_paginator,
            'categories': categories,
            'category': category,
        }

        return render(request, 'mainapp/interior-product.html', context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'page_title': 'products',
        'categories': categories,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/interior-product-hot.html', context)


def contact(request):


    with open('geekshop/locations.json', 'r', encoding='utf-8') as f:
        locations = json.load(f)

    context = {
        'page_title': 'interior: contacts',
        'locations': locations,
    }
    return render(request, 'mainapp/interior-contact.html', context)


def productdet(request, pk):
    categories = ProductCategory.objects.filter(is_active=True)
    product = get_object_or_404(Product, pk=pk)

    context = {
        'page_title': 'interior: product',
        'categories': categories,
        'product': product,
    }
    return render(request, 'mainapp/interior-product-details.html', context)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
{% load static %}

<ul class="tab-control">
    <li>
        <a href="{% url 'product:category' 0 %}"
           class="product_menu {% if request.resolver_match.kwargs.pk == 0 %} product_menu_active {% endif %}">
            ALL
        </a>
    </li>
    {% for category in categories %}
    <li>
        <a href="{% url 'product:category' category.pk %}"
           class="product_menu {% if request.resolver_match.kwargs.pk|add:'0' == category.pk %} product_menu_active {% endif %}">
            {{ category.name|title }}
        </a>
    </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
{% load staticfiles %}

<div class="header">
    <a href="/" class="logo"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main' %}" class="menu__link {% if request.resolver_match.url_name == 'main' %} menu__link_active {% endif %}">
                HOME
            </a>
        </li>
        <li>
            <a href="{% url 'product:index' %}" class="menu__link {% if request.resolver_match.namespace == 'product' or request.resolver_match.url_name == 'productdet' %} menu__link_active {% endif %}">
                PRODUCTS
            </a>
        </li>
        <li>
            <a href="#" class="menu__link {% if request.resolver_match.url_name == 'history' %} menu__link_active {% endif %}">
                HISTORY</a>
        </li>
        <li>
            <a href="#" class="menu__link {% if request.resolver_match.url_name == 'showrooms' %} menu__link_active {% endif %}">
                SHOWROOM</a>
        </li>
        <li>
            <a href="{% url 'contact' %}" class="menu__link {% if request.resolver_match.url_name == 'contact' %} menu__link_active {% endif %}">
                CONTACT
            </a>
        </li>
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle menu__link" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'User' }}
                    <span class="caret"></span>
                </a>
                <ul class = "dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            account
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            orders
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:users' %}" class="menu__link">admin panel</a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="menu__link">logout</a>
            {% else %}
            <a href = "{% url 'auth:login' %}" class="menu__link">login</a>
            {% endif %}
        </li>
        <li>
            <a href="#" class="menu__link">
                <i class="fas fa-search"></i>
            </a>
        </li>
        <li>
            <a href="{% url 'basket:view' %}" class="menu__link">
                <i class="fas fa-shopping-basket"></i>
                <span class="use_link">
                    {% if basket %}
                        $&nbsp;{{ basket.0.total_cost }} /
                        {{ basket.0.total_quantity|floatformat:0 }} items
                    {% endif %}
                </span>
            </a>
        </li>
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_promo.html
{% load static %}

<div class="promo">
    <div class="promo_img" style="background-image: url({% static 'img/promo-img1.jpg' %})">
        <div class="promo_content">
            <div class="color_text color_exclusive">exclusive</div>
            <h2 class="promo_h2">Fishnet Chair</h2>
            <p class="text_reg propmo_p">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
            <a href="#" class="button button_long">Order Us <i class="fas fa-chevron-right"></i></a>
        </div>
    </div>
    <div class="promo_img" style="background-image: url({% static 'img/promo-img.jpg' %})">
        <div class="promo_content">
            <div class="color_text color_exclusive">exclusive</div>
            <h2 class="promo_h2">Fishnet Chair</h2>
            <p class="text_reg propmo_p">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
            <a href="#" class="button button_long">Order Us <i class="fas fa-chevron-right"></i></a>
        </div>
    </div>
</div>