geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/',
         adminapp.ProductCategoryCreateView.as_view(),
         name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.ProductCategoryUpdateView.as_view(),
         name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.ProductCategoryDeleteView.as_view(),
         name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from django.urls import re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='product')),
    path('contacts/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory
from mainapp.models import Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'users/create'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()
    context = {
        'title': title,
        'update_form': user_form,
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'users/edit'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES,
                                          instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update',
                                                args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)
    context = {
        'title': title,
        'update_form': edit_form,
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'user/delete'

    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    context = {
        'title': title,
        'user_to_delete': user,
    }
    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'admin/categories'

    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/edit'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'admin/product'

    category = get_object_or_404(ProductCategory, pk=pk)

    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    context = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'product/ctreate'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products',
                                                args=[pk]))
    else:
        product_form = ProductEditForm(initial={'category': category})
    context = {
        'title': title,
        'update_form': product_form,
        'category': category,
    }
    return render(request, 'adminapp/product_update.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'product/edit'

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES,
                                    instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:product_update',
                                                args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)
    context = {
        'title': title,
        'update_form': edit_form,
        'category': edit_product.category
    }
    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = 'product/delete'

    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin:products',
                                            args=[product.category.pk]))
    context = {
        'title': title,
        'product_to_delete': product,
    }
    return render(request, 'adminapp/product_delete.html', context)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href = "{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href = "{% static 'css/style1.css' %}" >
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js%}

    {% endblock %}
</head>
<body>
    <div class="admin_container">
        <div class="h2 text-center head">
            admin panel
        </div>
        {% block menu %}
            <div class="admin_menu">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="categories_list">
		<button class="new_category">
			<a href={% url 'admin:category_create' %}>new category</a>
		</button>

		{% for object in objects %}
			<div class="category_record
				{% if not object.is_active %}
					not_active
				{% endif %}" >
				<div class="category_name">
					{{ object.name|title }}
				</div>
				<div class="category_actions">
					<button>
						<a href="{% url 'admin:products' object.pk %}">category products</a>
					</button>
					<button>
						<a href="{% url 'admin:category_update' object.pk %}">edit</a>
					</button>
					<button>
						<a href="{% url 'admin:category_delete' object.pk %}">delete</a>
					</button>
				</div>
				<div class="category_desc">
					{{ object.description|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="category_delete">
        Are you sure you want to delete {{ object.name }}?
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">cancel</a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="save">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:categories' %}">
            to category list
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="product_delete">
        Are you sure you want to delete product <strong>{{ product_to_delete.name }}</strong>?
        <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' product_to_delete.category.pk %}">
                cancel
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Product: <strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
        </div>
        <img src="{{ object.image|media_folder_products}}" alt="{{ object.name }}">
        <div class="summary">
            <b>price</b>
            <p>{{ object.price }}</p>
            <b>quantity</b>
            <p>{{ object.quantity }}</p>
            <b>in catalogue</b>
            <p>{% if object.is_active %}yes{% else %}no{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>edit</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>delete</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.category.pk %}>back</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>short description</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>Description</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="save">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:products' category.pk %}">
                to products
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


{% block content %}
    <div class="products_list">
		<button class="new_product">
			<a href={% url 'admin:product_create' category.pk %}>new product</a>
		</button>

		{% for object in objects %}
			<div class="product_record
				{% if not object.is_active %}
					not_active
				{% endif %}" >
				<img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
				<div class="product_name">
					{{ object.name|title }}
				</div>
				<div class="product_actions">
					<button>
						<a href={% url 'admin:product_read' object.pk %}>more</a>
					</button>
					<button>
						<a href={% url 'admin:product_update' object.pk %}>edit</a>
					</button>
					<button>
						<a href={% url 'admin:product_delete' object.pk %}>delete</a>
					</button>
				</div>
				<div class="summary">
					<b>price</b>
					<p>{{ object.price }}</p>
					<b>quantity</b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="product_desc">
					{{ object.short_desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="user_delete">
        Are you sure you want to delete {{ user_to_delete.username }} {% if user_to_delete.first_name %}
                    ({{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}?
        <form action="{% url 'admin:user_delete' user_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:users' %}">cancel</a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="save">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:users' %}">
            to users list
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


{% block content %}
    <div class="users_list">
		<button class="new_user">
			<a href="{% url 'admin:user_create' %}">new user</a>
		</button>
		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.avatar|media_folder_users }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}administrator{% else %}user{% endif %}
					<button>
						<a href="{% url 'admin:user_update' object.pk %}">edit</a>
					</button>
					<button>
						<a href="{% url 'admin:user_delete' object.pk %}">delete</a>
					</button>
				</div>
				<div class="user_name">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					<p>
					{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% if object.last_name %}
							<p>{{ object.last_name|title }}</p>
						{% endif %}
					{% endif %}
					</p>
				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} years
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}