geekshop/authapp/urls.py
from django.urls import path
from django.urls import re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='product')),
    path('contacts/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.product, name='index'),
    path('category/<int:pk>/', mainapp.product, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.product, name='page'),
    path('product-details/<int:pk>/', mainapp.productdet, name='productdet'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Category name',
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name="Description",
                                   blank=True)
    is_active = models.BooleanField(verbose_name='active', default=True)


    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Product name',
                            max_length=128)
    image = models.ImageField(upload_to='products_image', blank=True)
    short_desc = models.CharField(verbose_name='short product description',
                                  max_length = 100, blank=True)
    description = models.TextField(verbose_name='Product description',
                                   blank=True)
    price = models.DecimalField(verbose_name='Product price',
                                max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='storage quantity', default=0)
    is_active = models.BooleanField(verbose_name='active', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import json
import random
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from basketapp.models import Basket
from .models import ProductCategory, Product

# Create your views here.


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.filter(is_active=True,
                                      category__is_active=True)
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category,
                                           is_active=True,
                                           category__is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    products = Product.objects.filter(is_active=True,
                                      category__is_active=True)[:6]

    context = {
        'page_title': 'interior: home page',
        'products': products,
    }
    return render(request, 'mainapp/index.html', context)


def product(request, pk=None, page = 1):
    print(pk)
    categories = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).order_by('price')
            category = {
                'pk': 0,
                'name': 'all'
            }
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk,
                                              is_active=True,
                                              category__is_active=True).order_by('price')
        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(2)
        context = {
            'page_title': 'interior: products',
            'products': products_paginator,
            'categories': categories,
            'category': category,
        }

        return render(request, 'mainapp/interior-product.html', context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'page_title': 'products',
        'categories': categories,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/interior-product-hot.html', context)


def contact(request):


    with open('geekshop/locations.json', 'r', encoding='utf-8') as f:
        locations = json.load(f)

    context = {
        'page_title': 'interior: contacts',
        'locations': locations,
    }
    return render(request, 'mainapp/interior-contact.html', context)


def productdet(request, pk):
    categories = ProductCategory.objects.filter(is_active=True)
    product = get_object_or_404(Product, pk=pk)

    context = {
        'page_title': 'interior: product',
        'categories': categories,
        'product': product,
    }
    return render(request, 'mainapp/interior-product-details.html', context)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ page_title|title }}</title>
    {% block css%}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/8fece0c8ba.js"></script>
    {% endblock %}
    {% block js %}
        <script src = "{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock%}
</head>

<body>
    <div class="container">
        {% block top %}
        {% endblock %}
        {% block footer %}
        <div class="footer padding_site">
            <div class="fotter_content">
                <div class="contact_us">
                    <div class="color_text text_contact_us">Contact Us</div>
                    <div class="adress"> 132A Bridge Road Richmond VIC Australia.</div>
                    <div class="adress"> Talk to us on 1300 132 info@interior.com</div>
                </div>
                <div class="useful">
                    <div class="color_text text_contact_us">Useful Information</div>
                    <div class="usefull_links">
                        <a href="#" class="use_link">Sales terms</a>
                        <a href="#" class="use_link">Architect accounts</a>
                        <a href="#" class="use_link">Customer care</a>
                        <a href="#" class="use_link">Careers</a>
                        <a href="#" class="use_link">Delivery</a>
                        <a href="#" class="use_link">Exchanges &amp; returns</a>
                    </div>
                </div>
                <div class="stay_in_touch">
                    <div class="color_text text_contact_us">Let&rsquo;s Stay in&nbsp;Touch!</div>
                    <div class="adress"> Suscribe to know about our latest news, products and special offers just for suscribers.</div>
                    <form action="#" class="contact_form">
                        <input type="email" class="email" placeholder="your email address">
                        <a href="#" class="icon_link"><i class="fab fa-telegram-plane"></i></a>
                    </form>
                </div>
            </div>
            <div class="footer_footer">
                <div class="copyright">&copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2016. All Rights Reserved.</div>

                <div class="social">
                    <a href="#" class="social_link"><img src="{% static 'img/online%20social%20media%20facebook%20by%20alfredocreates.svg' %}" alt="facebook"></a>
                    <a href="#" class="social_link"><img src="{% static 'img/twitter%20online%20social%20media%20by%20alfredocreates.svg' %}" alt="twitter"></a>
                    <a href="#" class="social_link"><img src="{% static 'img/online%20social%20media%20google%20plus%20by%20alfredocreates.svg' %}" alt="google plus"></a>
                    <a href="#" class="social_link"><img src="{% static 'img/online%20social%20media%20pinterest%20by%20alfredocreates.svg' %}" alt="pinterest"></a>
                </div>
                <div class="copyright">Terms &amp;&nbsp;Conditions&nbsp;/ Privacy policy &amp;&nbsp;Cookies</div>

            </div>

        </div>
        {% endblock %}
    </div>
</body>

</html>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block top %}
<div class="top">
            <div class="slider slider_trending padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
                <div class="slider__content">
                    <div class="color_text color__trending">TRENDING</div>
                    <h2 class="slider__h2">Fishnet Chair</h2>
                    <p class="text_reg slider__p">
                        Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
                    </p>
                    <a href="#" class="button button_long">Order Us <i class="fas fa-chevron-right"></i></a>
                </div>
                <div class="slider__pagination">
                    <a href="#" class="circle"></a>
                    <a href="#" class="circle circle_active"></a>
                    <a href="#" class="circle"></a>
                </div>
            </div>
            <div class="featured-product padding_site">
                <div class="hading_featured">
                    <ul class="tab-control">
                        <li><a href="#" class="tab-control_link tab-control_active">Featured</a></li>
                        <li><a href="#" class="tab-control_link">New</a></li>
                    </ul>
                    <a href="{% url 'product:index' %}" class="btn_ghost">explore all <i class="fas fa-chevron-right"></i></a>
                </div>
                <div class="tab_content">
                    <div class="tab_product" style="background-image: url({% static 'img/product-1.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-2.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-3.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-4.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'mainapp/includes/inc_promo.html' %}
            <div class="trending padding_site">
                <div class="hading_trending">
                    <h2 class="trending_h2">Trending Products</h2>
                    <a href="{% url 'product:index' %}" class="btn_ghost">explore all <i class="fas fa-chevron-right"></i></a>
                </div>
                <div class="tab_content">
                    {% for prod in products%}
                    <div class="trending_product" style="background-image: url({{ prod.image|media_folder_products}})">
                        <div class="product_content">
                            <a href="{% url 'product:productdet' prod.pk %}" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">{{ prod.name }}</h2>
                            <p class="text_reg text_product">{{ prod.short_desc }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="slider slider_hot_deal padding_site">
                <div class="slider__content">
                    <div class="color_text color__hot_deal">Hot deal</div>
                    <h2 class="slider__h2">Fishnet Chair</h2>
                    <p class="text_reg slider__p">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.
                    </p>
                    <a href="#" class="button button_long">Order Us <i class="fas fa-chevron-right"></i></a>
                </div>
                <div class="slider__pagination">
                    <a href="#" class="circle"></a>
                    <a href="#" class="circle circle_active"></a>
                    <a href="#" class="circle"></a>
                </div>
            </div>
            <div class="exclusive_product padding_site">
                <div class="exclusive_img" style="background-image: url({% static 'img/product-1-lg.jpg' %})">
                    <div class="promo_content">
                        <div class="color_text color_exclusive">exclusive</div>
                        <h2 class="promo_h2">Fishnet Chair</h2>
                        <p class="text_reg propmo_p">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        <a href="#" class="button button_long">Order Us <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
                <div class="exclusive_img exclusive_small">
                    <div class="tab_product" style="background-image: url({% static 'img/product-2-sm.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-3-sm.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-4-sm.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                    <div class="tab_product" style="background-image: url({% static 'img/product-5-sm.jpg' %})">
                        <div class="product_content">
                            <a href="#" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">Fishnet Chair</h2>
                            <p class="text_reg text_product">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mobile_app padding_site">
                <div class="mobile_app_content">
                    <div class="color_text color__mobile">mobile app</div>
                    <h2 class="slider__h2 mobile-app_h2">Find. Follow. Favorite.</h2>
                    <p class="mobile_app_text">Save your favorites and share your style.</p>
                    <a href="#" class="app_store"><img src="{% static 'img/app-store.svg' %}" alt="app-store link"></a>
                    <a href="#" class="app_store"><img src="{% static 'img/google-play.svg' %}" alt="google-play link"></a>
                </div>

            </div>
        </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/interior-contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block top %}
<div class="top">
            <div class="header_menu padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
                <h2 class="slider__h2 interior_header">Contact Us</h2>
            </div>
            <div class="contacts padding_site">
            {% for item in locations %}
                <div class="adress_link">
                    <a href="#" class="location_link"><i class="fas fa-map-marker-alt"></i></a>
                    <p class="state">{{ item.state }}</p>
                    <p class="contats">Phone:</p>
                    <p class="contact_details">{{ item.phone }}</p>
                    <p class="contats">Email:</p>
                    <p class="contact_details">{{ item.email }}</p>
                    <p class="contats">Address:</p>
                    <p class="adress_details">{{ item.address }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/interior-product-details.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block top %}
<div class="top">
            <div class="product_details_menu padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
            </div>
            <div class="product_information_menu">
                {% include 'mainapp/includes/inc_categories_menu.html' %}
            </div>
            <div class="product_information padding_site">
                <div class="product_slider">
                    <div class="product_slider_big" style="background-image: url({{ product.image|media_folder_products}})"></div>
                    <div class="product_slider_elem">
                        <div class="product_slider_small" style="background-image: url({{ product.image|media_folder_products}})"></div>
                        <div class="product_slider_small" style="background-image: url({{ product.image|media_folder_products}})"></div>
                        <div class="product_slider_small" style="background-image: url({{ product.image|media_folder_products}})"></div>
                    </div>

                </div>
                <h2 class="product_details-name float">{{ product.name }}</h2>
                <div class="product_info_hot float">Hot Deal</div>
                <div class="price float">$&nbsp;<span class="price_font">{{ product.price }}</span>/sq</div>
                <a href="{% url 'basket:add' product.pk %}" class="button_product float">Order Us <i class="fas fa-chevron-right"></i></a>
                <p class="product_description">{{ product.description }}</p>
            </div>
        </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/interior-product-hot.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block top %}
<div class="top">
            <div class="product_details_menu padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
            </div>
            <div class="product_information_menu">
                {% include 'mainapp/includes/inc_categories_menu.html' %}
            </div>
            <div class="product_information padding_site">
                <div class="product_slider">
                    <div class="product_slider_big" style="background-image: url({{ hot_product.image|media_folder_products}})"></div>
                    <div class="product_slider_elem">
                        <div class="product_slider_small" style="background-image: url({{ hot_product.image|media_folder_products}})"></div>
                        <div class="product_slider_small" style="background-image: url({{ hot_product.image|media_folder_products}})"></div>
                        <div class="product_slider_small" style="background-image: url({{ hot_product.image|media_folder_products}})"></div>
                    </div>

                </div>
                <h2 class="product_details-name float">{{ hot_product.name }}</h2>
                <div class="product_info_hot float">Hot Deal</div>
                <div class="price float">$&nbsp;<span class="price_font">{{ hot_product.price }}</span>/sq</div>
                <a href="{% url 'basket:add' hot_product.pk %}" class="button_product float">Order Us <i class="fas fa-chevron-right"></i></a>
                <p class="product_description">{{ hot_product.description }}</p>
            </div>
            <div class="trending padding_site">
                <div class="hading_trending">
                    <h2 class="trending_h2">Related Products</h2>
                    <a href="#" class="btn_ghost">explore all <i class="fas fa-chevron-right"></i></a>
                </div>
                <div class="tab_content">
                    {% for prod in same_products%}
                    <div class="trending_product" style="background-image: url({{ prod.image|media_folder_products}})">
                        <div class="product_content">
                            <a href="{% url 'product:productdet' prod.pk %}" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">{{ prod.name }}</h2>
                            <p class="text_reg text_product">{{ prod.short_desc }}</p>
                        </div>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/interior-product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block top %}
<div class="top">
            <div class="header_menu padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
                <h2 class="slider__h2 interior_header">Our Products Range</h2>
            </div>
            <div class="products padding_site">
                <div class="hading_featured">
                    {% include 'mainapp/includes/inc_categories_menu.html' %}
                </div>
                <div class="products_list">
                    <div class="title clearfix">
                        <h2>Category: "{{ category.name|title }}"</h2>
                        <div class="'paginator">
                            {% if products.has_previous %}
                                <a href="{% url 'product:page' category.pk products.previous_page_number %}">
                                    <
                                </a>
                            {% endif %}
                            <span class="current">
                                page {{ products.number }} from {{ products.paginator.num_pages }}
                            </span>
                            {% if products.has_next %}
                                <a href="{% url 'product:page' category.pk products.next_page_number %}">
                                    >
                                </a>
                            {% endif %}
                        </div>
                    </div>

                </div>
                <div class="tab_content">
                    {% for prod in products%}
                    <div class="trending_product" style="background-image: url({{ prod.image|media_folder_products}})">
                        <div class="product_content">
                            <a href="{% url 'product:productdet' prod.pk %}" class="button btn_circle"><i class="fas fa-chevron-right chevron-circle"></i></a>
                            <h2 class="product_name">{{ prod.name }}</h2>
                            <p class="text_reg text_product">{{ prod.short_desc }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="refresh_circle">
                    <a href="#" class="refresh"><i class="fas fa-sync-alt"></i></a>
                </div>

            </div>
            {% include 'mainapp/includes/inc_promo.html' %}
        </div>
{% endblock %}